import {useEffect,useRef,useState} from "react";
import {ArrowLeft,ArrowUpRight,BookOpen,Feather,FileText,Globe2,Plus,Sparkles,Square,Trash2,X} from "lucide-react";
import {request,type BookSummary} from "./reading-api";
import "./author-studio.css";

type Work={id:string;title:string;text:string;written:string;published:string;revised:string;revises:string;genre:string;audience:string;language:string;kind:string;attribution:string;source:string;private:boolean};
type Observation={id:string;kind:string;text:string;period:string;evidence:string[];counter_evidence:string[];uncertainty:string};
type Analysis={version:number;work_ids:string[];observations:Observation[];changes:string;warnings:string[]};
type Draft={id:string;title:string;text:string;edited:string;brief:string;style:string;facts:string;warnings:string[];analysis_version:number};
type Author={id:string;name:string;aliases:string;revision:number;works:Work[];analyses:Analysis[];drafts:Draft[]};
type Chunk={id:string;work:string;text:string};
type SearchHit={title:string;url:string;snippet?:string};
const kindLabels:Record<string,string>={fact:"可核验信息",expression:"明确表达",style:"文本风格",hypothesis:"解释性假设"};
const emptyWork=():Partial<Work>=>({title:"",text:"",source:"",written:"",published:"",revised:"",revises:"",genre:"",audience:"",language:"zh",kind:"original",attribution:"用户提供，作者归属待核验",private:true});
async function streamAuthor(path:string,body:unknown,signal:AbortSignal,status:(s:string)=>void):Promise<Author>{
 const res=await fetch(`/api/story${path}`,{method:"POST",credentials:"same-origin",headers:{...readerHeaders(),"Content-Type":"application/json"},body:JSON.stringify(body),signal});if(!res.ok)checkReaderResponse(res.status);if(!res.ok||!res.body)throw Error("作者任务未能启动");
 const reader=res.body.getReader(),decoder=new TextDecoder();let buffer="",result:Author|undefined;
 const line=(s:string)=>{if(!s.trim())return;const e=JSON.parse(s);if(e.type==="status")status(e.data.message);if(e.type==="error")throw Error(e.data.message);if(e.type==="result")result=e.data;};
 try{while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value,{stream:!done});let n:number;while((n=buffer.indexOf("\n"))>=0){line(buffer.slice(0,n));buffer=buffer.slice(n+1);}if(done){line(buffer);break;}}}finally{reader.releaseLock();}
 if(!result)throw Error("没有收到任务保存确认，请重新打开档案核对");return result;
}

export function AuthorStudio(){
 const [deleteConfirm,setDeleteConfirm]=useState(false);
 const evidenceDialog=useRef<HTMLElement|null>(null);
 const [authors,setAuthors]=useState<Author[]>([]),[books,setBooks]=useState<BookSummary[]>([]),[author,setAuthor]=useState<Author>(),[chunks,setChunks]=useState<Record<string,Chunk>>({});
 const [tab,setTab]=useState<"works"|"understanding"|"writing">("works"),[name,setName]=useState(""),[aliases,setAliases]=useState("");
 const [work,setWork]=useState<Partial<Work>>(emptyWork),[showImport,setShowImport]=useState(false),[fetchURL,setFetchURL]=useState(false),[bookID,setBookID]=useState("");
 const [busy,setBusy]=useState(""),[error,setError]=useState(""),[consent,setConsent]=useState(false),[version,setVersion]=useState(0),[evidence,setEvidence]=useState<Chunk>();
 const [selected,setSelected]=useState<string[]>([]),[brief,setBrief]=useState(""),[style,setStyle]=useState(""),[facts,setFacts]=useState(""),[edit,setEdit]=useState(""),[draftID,setDraftID]=useState("");
 const [query,setQuery]=useState(""),[publicSearch,setPublicSearch]=useState(false),[hits,setHits]=useState<SearchHit[]>([]);const cancel=useRef<AbortController|null>(null);
 const loadList=()=>request<Author[]>("/authors").then(setAuthors);
 useEffect(()=>{
  if(!evidence&&!deleteConfirm)return;
  const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;
  const close=evidenceDialog.current?.querySelector<HTMLButtonElement>("button");
  close?.focus();
  const key=(event:KeyboardEvent)=>{
   if(event.key==="Escape"){event.preventDefault();setEvidence(undefined);setDeleteConfirm(false);}
   if(event.key==="Tab"){
    const buttons=Array.from(evidenceDialog.current?.querySelectorAll<HTMLButtonElement>("button:not(:disabled)")||[]);
    const index=buttons.indexOf(document.activeElement as HTMLButtonElement);
    event.preventDefault();buttons[(index+(event.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus();
   }
  };
  document.addEventListener("keydown",key);
  return()=>{document.removeEventListener("keydown",key);previous?.focus();};
 },[evidence,deleteConfirm]);
 const open=async(id:string)=>{const d=await request<{author:Author;chunks:Record<string,Chunk>}>(`/authors/${id}`);setAuthor(d.author);setChunks(d.chunks);setVersion(d.author.analyses.length);setSelected([]);setConsent(false);setDraftID("");setEdit("");const url=new URL(location.href);url.searchParams.set("author",id);history.replaceState({},"",url);};
 useEffect(()=>{let active=true;(async()=>{const list=await request<Author[]>("/authors");if(!active)return;setAuthors(list);setBooks(await request<BookSummary[]>("/books"));const id=new URLSearchParams(location.search).get("author");if(id&&active)await open(id);})().catch(e=>setError(e.message));return()=>{active=false;cancel.current?.abort();};},[]);
 const act=async(label:string,fn:()=>Promise<void>)=>{if(busy)return;setBusy(label);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"操作失败");}finally{setBusy("");}};
 const create=()=>act("建立作者档案",async()=>{const a=await request<Author>("/authors",{name,aliases});await loadList();await open(a.id);setName("");setAliases("");});
 const deleteAuthor=()=>act("正在删除作者档案",async()=>{
  if(!author)return;
  await request(`/authors/${author.id}/delete`,{revision:author.revision});
  setAuthors(list=>list.filter(a=>a.id!==author.id));setAuthor(undefined);setChunks({});setEvidence(undefined);setDeleteConfirm(false);
  setSelected([]);setConsent(false);setVersion(0);setDraftID("");setEdit("");setTab("works");setShowImport(false);setWork(emptyWork());setHits([]);setQuery("");setPublicSearch(false);setBrief("");setStyle("");setFacts("");setBookID("");setFetchURL(false);
  const url=new URL(location.href);url.searchParams.delete("author");history.replaceState({},"",url);
 });
 const refresh=async(a:Author)=>{await open(a.id);await loadList();};
 const analyze=()=>act("正在开始逐篇阅读",async()=>{if(!author)return;const controller=new AbortController();cancel.current=controller;try{const a=await streamAuthor(`/authors/${author.id}/analyze`,{revision:author.revision,consent},controller.signal,setBusy);await refresh(a);setTab("understanding");}catch(e){if(controller.signal.aborted){await open(author.id);throw Error("已停止等待。完成的片段阅读会保留，下次分析可继续复用。");}throw e;}finally{cancel.current=null;}});
 const write=()=>act("正在准备新的文字",async()=>{if(!author)return;const controller=new AbortController();cancel.current=controller;try{const a=await streamAuthor(`/authors/${author.id}/write`,{revision:author.revision,consent,observation_ids:selected,brief,style,facts},controller.signal,setBusy);await refresh(a);const d=a.drafts[a.drafts.length-1];setDraftID(d.id);setEdit(d.edited||d.text);}catch(e){if(controller.signal.aborted){await open(author.id);throw Error("已停止；仅保留服务器确认保存的稿件。");}throw e;}finally{cancel.current=null;}});
 const demo=()=>act("打开预生成的真实模型演示，不发起新的分析",async()=>{
  await refresh(await request<Author>("/authors/demo",{}));
  setTab("understanding");
 });
 const current=author?.analyses.find(a=>a.version===version),latest=author?.analyses[author.analyses.length-1],draft=author?.drafts.find(d=>d.id===draftID);
 const field=(key:keyof Work,value:unknown)=>setWork(w=>({...w,[key]:value}));
 return <main className="aw-room"><header className="aw-header"><a href="/reading"><ArrowLeft size={17}/>返回书架</a><span><Feather size={20}/>作者工作台</span></header>
  <div className="aw-layout"><aside className="aw-library"><h1>作者档案</h1><p>整理作品、年代和原文依据，分析作者的表达。</p><nav aria-label="作者档案">{authors.map(a=><button disabled={!!busy} className={author?.id===a.id?"active":""} key={a.id} onClick={()=>act("打开作者档案",()=>open(a.id))}><span>{a.name}</span><small>{a.works.length} 篇作品 · {a.analyses.length} 次认识</small></button>)}</nav><form onSubmit={e=>{e.preventDefault();if(name.trim())create();}}><label>新作者<input aria-label="作者姓名" value={name} onChange={e=>setName(e.target.value)} placeholder="姓名或笔名" maxLength={100}/></label><input aria-label="作者别名" value={aliases} onChange={e=>setAliases(e.target.value)} placeholder="别名 / 归属说明（选填）" maxLength={300}/><button disabled={!!busy||!name.trim()}><Plus size={15}/>建立档案</button></form><button className="aw-demo" disabled={!!busy} onClick={demo}>打开已完成的虚构演示<ArrowUpRight size={14}/></button><small className="aw-private">本地私人工作区 · 未加密落盘<br/>作品不自动成为角色或安的记忆。</small></aside>
  <section className="aw-main">{busy&&<div className="aw-status" role="status"><Sparkles size={16}/>{busy}{cancel.current&&<button onClick={()=>cancel.current?.abort()}><Square size={12}/>停止</button>}</div>}{error&&<p className="aw-error" role="alert">{error}</p>}
   {!author?<div className="aw-empty"><span>“</span><h2>一个人，会在不同的时间，<br/>写下不同的自己。</h2><p>从左侧建立作者档案，加入旧文章。安会逐篇阅读，寻找表达、风格与变化，再将这些认识用于新的创作。</p><div><article><FileText/><h3>作品档案</h3><p>写了什么，何时写下，版本与来源。</p></article><article><BookOpen/><h3>逐步理解</h3><p>每项判断都有原文，也保留反例。</p></article><article><Feather/><h3>风格创作</h3><p>借鉴表达方式，写自己的新内容。</p></article></div><label>也可以从书架作者开始<select aria-label="选择书架作者" value="" onChange={e=>{setName(e.target.value);}}><option value="">选择一位作者</option>{[...new Set(books.map(b=>b.author))].map(n=><option key={n}>{n}</option>)}</select></label></div>:<>
    <div className="aw-title"><div><span className="aw-kicker">AUTHOR'S DOSSIER</span><h2>{author.name}</h2><p>{author.aliases||"作品会变化，我们的认识也应如此。"}</p></div><div><b>{author.works.length}</b><small>篇作品</small><b>{author.analyses.length}</b><small>个认识版本</small><button className="aw-delete-author" disabled={!!busy} onClick={()=>{setError("");setEvidence(undefined);setDeleteConfirm(true);}}><Trash2 size={15}/>删除作者</button></div></div>
    <p className="aw-privacy-note">本档案及上传作品只属于当前登录名字，不向其他名字共享。书架自带原文是共享资源；“私人资料”选项控制联网处理，不是公开开关。</p>
    <nav className="aw-tabs" aria-label="作者工作台视图">{([['works','作品与时间线'],['understanding','安的作者认识'],['writing','风格创作']] as const).map(([id,label])=><button className={tab===id?"active":""} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==="works"&&<><div className="aw-section-title"><h3>什么时间，写下了什么</h3><button disabled={!!busy} onClick={()=>setShowImport(!showImport)}><Plus size={15}/>加入作品</button></div>
     {showImport&&<section className="aw-import"><h3>加入原始资料</h3><p>留空的年代按未知保留。原作、译文、合著与转载会分别对待。</p><div className="aw-form-grid"><label>标题<input value={work.title} onChange={e=>field("title",e.target.value)} maxLength={200}/></label><label>材料类型<select value={work.kind} onChange={e=>field("kind",e.target.value)}>{Object.entries({original:"原作",translation:"译文",edited:"编辑加工",coauthored:"合著",reprint:"转载",uncertain:"作者归属存疑"}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>写作时间<input placeholder="年份、范围，或留空" value={work.written} onChange={e=>field("written",e.target.value)}/></label><label>首次发表<input value={work.published} onChange={e=>field("published",e.target.value)}/></label><label>修订时间<input value={work.revised} onChange={e=>field("revised",e.target.value)}/></label><label>修订自<select value={work.revises} onChange={e=>field("revises",e.target.value)}><option value="">独立作品</option>{author.works.map(w=><option value={w.id} key={w.id}>{w.title}</option>)}</select></label><label>文体<input value={work.genre} onChange={e=>field("genre",e.target.value)} placeholder="随笔、评论、小说…"/></label><label>目标读者<input value={work.audience} onChange={e=>field("audience",e.target.value)}/></label><label>语言<input value={work.language} onChange={e=>field("language",e.target.value)}/></label><label>归属说明<input value={work.attribution} onChange={e=>field("attribution",e.target.value)}/></label></div><label>来源网址或版本说明<input value={work.source} onChange={e=>field("source",e.target.value)}/></label><label className="aw-check"><input type="checkbox" checked={!!work.private} onChange={e=>{field("private",e.target.checked);if(e.target.checked)setFetchURL(false);}}/>私人资料：不自动联网</label><label className="aw-check"><input type="checkbox" checked={fetchURL} disabled={!!work.private} onChange={e=>setFetchURL(e.target.checked)}/>主动读取上面的公开网页（计入联网额度）</label>{!fetchURL&&<><label>正文<textarea aria-label="作品正文" rows={8} value={work.text} onChange={e=>field("text",e.target.value)}/></label><label>或导入 TXT / Markdown<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>512*1024){setError("单篇正文上限512 KiB");return;}try{field("text",await f.text());if(!work.title)field("title",f.name);}catch{setError("文件读取失败");}}}/></label></>}<button className="aw-primary" disabled={!!busy||(!fetchURL&&(!work.title?.trim()||!work.text?.trim()))} onClick={()=>act("保存作品，不调用模型",async()=>{const a=await request<Author>(`/authors/${author.id}/works`,{revision:author.revision,work,fetch_url:fetchURL});await refresh(a);setWork(emptyWork());setShowImport(false);})}>保存到作品库</button>
      {books.some(b=>b.author===author.name)&&<div className="aw-book-import"><label>导入书架中已有原文<select value={bookID} onChange={e=>setBookID(e.target.value)}><option value="">选择作品</option>{books.filter(b=>b.author===author.name).map(b=><option value={b.id} key={b.id}>{b.title}</option>)}</select></label><button disabled={!!busy||!bookID} onClick={()=>act("导入内置原文",async()=>{await refresh(await request<Author>(`/authors/${author.id}/works`,{revision:author.revision,book_id:bookID}));setShowImport(false);})}>导入</button></div>}
     </section>}
     <div className="aw-timeline">{[...author.works].sort((a,b)=>(a.written||a.published||"9999").localeCompare(b.written||b.published||"9999")).map(w=><article key={w.id}><time>{w.written||"写作时间未知"}</time><div><span className="aw-tag">{w.genre||"文体待补充"} · {w.kind} {w.private?"· 私人":""}</span><h3>{w.title}</h3><p>{w.attribution}</p><small>发表：{w.published||"未知"} · 修订：{w.revised||"未知"} · 读者：{w.audience||"未标注"}</small><details><summary>阅读原文与来源</summary><p>{w.source||"用户提供，来源待核验"}</p><pre>{w.text}</pre></details></div></article>)}{!author.works.length&&<p className="aw-muted">先加入一篇作品。单篇认识会保持有限，不伪装成完整人格。</p>}</div>
     <details className="aw-search"><summary><Globe2 size={15}/>查找公开作品</summary><p>候选网页不是证据；需要主动读取并确认作者归属后加入作品库。私人档案不发送搜索查询。</p><input aria-label="公开作品搜索词" value={query} onChange={e=>setQuery(e.target.value)} placeholder="作品标题 / 原文 / 出版信息" maxLength={160}/><label className="aw-check"><input type="checkbox" checked={publicSearch} onChange={e=>setPublicSearch(e.target.checked)}/>确认这是公开作者的公开资料查询</label><button disabled={!!busy||!publicSearch||!query.trim()} onClick={()=>act("查找公开来源",async()=>setHits(await request<SearchHit[]>(`/authors/${author.id}/search`,{query,public:publicSearch}))) }>搜索</button>{hits.map(h=><article key={h.url}><a href={h.url} target="_blank" rel="noreferrer">{h.title||h.url} ↗</a><p>{h.snippet}</p><button onClick={()=>{setWork({...emptyWork(),title:h.title,source:h.url,private:false,kind:"uncertain"});setFetchURL(true);setShowImport(true);}}>作为待核验来源</button></article>)}</details>
     <div className="aw-analysis-action"><label className="aw-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意将本档案作品发送至当前配置的模型网关分析；私人资料也会发送，文件本地未加密。</label><button className="aw-primary" disabled={!!busy||!consent||!author.works.length} onClick={analyze}><Sparkles size={16}/>让安逐篇阅读并更新认识</button><small>逐批读取全文，保留检查点。不会在导入时自动调用模型。</small></div>
    </>}
    {tab==="understanding"&&(!current?<div className="aw-empty-small"><BookOpen/><h3>认识还没有开始</h3><p>先加入作品，再让安阅读。这里不会预填假装已经分析过的作者标签。</p><button onClick={()=>setTab("works")}>回到作品库</button></div>:<><div className="aw-section-title"><h3>在这些文字里，我们看到了什么</h3><label>认识版本<select aria-label="认识版本" value={version} onChange={e=>setVersion(Number(e.target.value))}>{author.analyses.map(a=><option key={a.version} value={a.version}>v{a.version} · {a.work_ids.length}篇作品</option>)}</select></label></div><section className="aw-change"><span className="aw-kicker">WHAT CHANGED</span><p>{current.changes||"第一版有证据的认识。"}</p></section><div className="aw-observations">{current.observations.map(o=><article key={o.id}><span className={`aw-tag ${o.kind}`}>{kindLabels[o.kind]}</span><small>{o.period||"时期未确定"}</small><h3>{o.text}</h3>{o.uncertainty&&<p>{o.uncertainty}</p>}<div className="aw-citations">依据 {o.evidence.map((cid,i)=><button key={cid} onClick={()=>setEvidence(chunks[cid])}>{i+1} · {author.works.find(w=>w.id===chunks[cid]?.work)?.title||"片段"}</button>)}</div>{o.counter_evidence?.length>0&&<div className="aw-citations counter">反例 {o.counter_evidence.map(cid=><button key={cid} onClick={()=>setEvidence(chunks[cid])}>查看相反表达</button>)}</div>}</article>)}</div>{current.warnings?.map((w,i)=><p className="aw-warning" key={i}>{w}</p>)}<button className="aw-primary" onClick={()=>{setTab("writing");setSelected([]);}}>借鉴表达方式，开始新创作<Feather size={16}/></button></>)}
    {tab==="writing"&&<div className="aw-writing"><section><h3>借鉴风格，不借用身份</h3><p>选择当前认识中的表达特征，再告诉安：你想写什么，哪些地方需要不同。</p>{!latest&&<p>先阅读分析作品，才会出现有依据的风格特征。</p>}<div className="aw-style-options">{latest?.observations.filter(o=>o.kind==="style").map(o=><label key={o.id}><input type="checkbox" checked={selected.includes(o.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,o.id]:v.filter(id=>id!==o.id))}/><span>{o.text}<small>{o.period} · {o.uncertainty}</small></span></label>)}</div><label>新文档的任务、时期、文体与读者<textarea aria-label="创作任务" value={brief} onChange={e=>setBrief(e.target.value)} placeholder="例如：写一篇面向同事的短随笔，谈一次学会慢下来的经历。明确哪些情节可虚构。" maxLength={3000}/></label><label>调整表达方式<textarea aria-label="风格调整" value={style} onChange={e=>setStyle(e.target.value)} placeholder="保留短句和具体物象，减少感伤，不模仿个人经历。" maxLength={4000}/></label><label>这次写作的事实材料（不是作者的旧经历）<textarea aria-label="写作事实" value={facts} onChange={e=>setFacts(e.target.value)} maxLength={12000} placeholder="事实、原稿与来源。资料不足时保留未知；虚构写作请明确说明。"/></label><label className="aw-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>同意将以上输入及选定风格证据发送至当前模型服务。</label><button className="aw-primary" disabled={!!busy||!consent||!selected.length||!brief.trim()} onClick={write}><Feather size={16}/>生成新的草稿</button></section><section className="aw-drafts"><h3>你的新文字</h3><p>AI 辅助创作，不是原作者的新作。生成内容不会作为作者认识的证据。</p><select aria-label="选择草稿" value={draftID} onChange={e=>{setDraftID(e.target.value);const d=author.drafts.find(x=>x.id===e.target.value);setEdit(d?.edited||d?.text||"");}}><option value="">选择已保存的草稿</option>{author.drafts.map(d=><option value={d.id} key={d.id}>{d.title}</option>)}</select>{draft&&<><span className="aw-kicker">AI ASSISTED · 认识 v{draft.analysis_version}</span><h2>{draft.title}</h2>{draft.warnings?.map((w,i)=><p className="aw-warning" key={i}>{w}</p>)}<details><summary>查看模型原稿</summary><pre>{draft.text}</pre></details><label>你的修订<textarea aria-label="修订草稿" value={edit} onChange={e=>setEdit(e.target.value)} maxLength={16000}/></label><button disabled={!!busy} onClick={()=>act("保存人工修订",async()=>{await refresh(await request<Author>(`/authors/${author.id}/drafts/${draft.id}`,{revision:author.revision,text:edit}));setDraftID(draft.id);setEdit(edit);})}>保存修订</button></>}</section></div>}
   </>}
  </section></div>{evidence&&<div className="aw-backdrop"><section ref={evidenceDialog} role="dialog" aria-modal="true" aria-label="作者认识的原文依据"><button aria-label="关闭原文依据" onClick={()=>setEvidence(undefined)}><X size={20}/></button><span className="aw-kicker">原文依据</span><h2>{author?.works.find(w=>w.id===evidence.work)?.title}</h2><small>{evidence.id.split(":")[1]} · 原文片段，不是生成摘要</small><pre>{evidence.text}</pre></section></div>}
 {deleteConfirm&&author&&<div className="aw-backdrop"><section ref={evidenceDialog} role="alertdialog" aria-modal="true" aria-labelledby="delete-author-title"><h2 id="delete-author-title">删除「{author.name}」？</h2><p>将移除当前名字下的整个作者档案，包括 {author.works.length} 篇作品、{author.analyses.length} 个认识版本、{author.drafts.length} 份草稿和阅读检查点。</p><p>不会删除书架自带原文或其他名字的记录。资料移到本地回收目录，可由管理员恢复；这不是永久擦除。</p><div className="aw-delete-actions"><button disabled={!!busy} onClick={()=>setDeleteConfirm(false)}>取消，保留档案</button><button className="aw-delete-author" disabled={!!busy} onClick={deleteAuthor}>{busy?"正在删除…":"确认删除作者"}</button></div>{error&&<p className="aw-error">{error}</p>}</section></div>}
 </main>;
}
import {readerHeaders,checkReaderResponse} from "./reading-session";
