import {useEffect, useRef, useState} from "react";
import {ArrowLeft, ArrowRight, BookOpen, Bookmark, Check, Feather, Globe2, Languages, LoaderCircle, MessageCircle, Send, Sparkles, Square, X} from "lucide-react";
import {request, type Book, type Character} from "./reading-api";
import "./companion.css";
import "./companion-lessons.css";
import {LessonGuide} from "./LessonGuide";
import type {ReadingLesson} from "./ReadingLessonPage";
import {CompanionCost, type CompanionMetrics} from "./CompanionCost";
import {readerHeaders,checkReaderResponse} from "./reading-session";
import {BookTranslationBar,SentenceTranslation,useBookTranslation} from "./BookTranslation";

type Paragraph={id:number;text:string;start_byte:number;end_byte:number};
type Position={paragraph:number;furthest:number;full:boolean;finished:boolean;bookmarks:number[]};
type Source={id:string;title:string;url:string;summary:string};
type Turn={id:string;speaker:string;paragraph:number;full:boolean;action:string;message:string;reply:string;needs_spoiler:boolean;research_status?:string;sources:Source[];evidence:number[];metrics?:CompanionMetrics};
export type ReaderState={revision:number;version:string;position:Position;turns:Turn[];notes:{id:string;paragraph:number;text:string}[]};
type Loaded={state:ReaderState;paragraphs:Paragraph[];characters?:Record<number,Character[]>;research_available:boolean;research_provider?:string};

async function conversation(body:unknown,signal:AbortSignal,status:(s:string)=>void,metrics:(m:CompanionMetrics)=>void):Promise<ReaderState>{
 const url=new URL("/api/story/companion/chat",location.origin);url.searchParams.set("book",new URLSearchParams(location.search).get("book")||"necklace");
 const response=await fetch(url,{method:"POST",headers:{...readerHeaders(),"Content-Type":"application/json"},body:JSON.stringify(body),credentials:"same-origin",signal});
 if(!response.ok)checkReaderResponse(response.status);
 if(!response.ok||!response.body)throw Error("伴读暂未连接，请重试");
 const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="",result:ReaderState|undefined;
 const consume=(line:string)=>{if(!line.trim())return;const event=JSON.parse(line);if(event.type==="status")status(event.data.message);if(event.type==="metrics")metrics(event.data);if(event.type==="error")throw Error(event.data.message);if(event.type==="result")result=event.data;};
 try{while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value,{stream:!done});let split:number;while((split=buffer.indexOf("\n"))>=0){consume(buffer.slice(0,split));buffer=buffer.slice(split+1);}if(done){consume(buffer);break;}}}finally{reader.releaseLock();}
 if(!result)throw Error("回答中断，没有收到保存确认");return result;
}

export function CompanionReader({book,onStory,initialIntent,onLesson,continuous=false,lesson,lessonError}:{book:Book;onStory:()=>void;initialIntent?:{speaker:string;message:string;paragraph?:number};onLesson?:()=>void;continuous?:boolean;lesson?:ReadingLesson;lessonError?:string}){
 const [attemptMetrics,setAttemptMetrics]=useState<CompanionMetrics>();
 const [lineHeight,setLineHeight]=useState("1.9"),[collapsed,setCollapsed]=useState(false),[contextOpen,setContextOpen]=useState(false);
 const [data,setData]=useState<Loaded>();const [speaker,setSpeaker]=useState(initialIntent?.speaker||"an");const [input,setInput]=useState(initialIntent?.message||"");const [busy,setBusy]=useState("");const [error,setError]=useState("");
 const [display,setDisplay]=useState("original");const [font,setFont]=useState(20);const [research,setResearch]=useState(true);const [panel,setPanel]=useState<"chat"|"notes"|"guide">("chat");const [mobile,setMobile]=useState(!!initialIntent?.message);const [note,setNote]=useState("");const [style]=useState("fluent");
 const [finishDialog,setFinishDialog]=useState(false);const [reveal,setReveal]=useState(false);const abort=useRef<AbortController|null>(null);const bottom=useRef<HTMLDivElement>(null);
 const paper=useRef<HTMLElement>(null);
 const bookTranslation=useBookTranslation(book.id,style,book.language);
 const reload=()=>request<Loaded>("/companion").then(setData);
 useEffect(()=>{let live=true;request<Loaded>("/companion").then(async d=>{
  if(!live)return;
  const target=initialIntent?.paragraph;
  if(target&&d.paragraphs.some(p=>p.id===target)&&d.state.position.paragraph!==target){
   d={...d,state:await request<ReaderState>("/companion/position",{position:{...d.state.position,paragraph:target},revision:d.state.revision})};
  }
  if(live)setData(d);
 }).catch(e=>{if(live)setError(e.message);});return()=>{live=false;abort.current?.abort();};},[book.id]);
 useEffect(()=>{if(data&&initialIntent?.paragraph)paper.current?.querySelector(`[data-paragraph="${initialIntent.paragraph}"]`)?.scrollIntoView?.({block:"start"});},[!!data]);
 useEffect(()=>{bottom.current?.scrollIntoView?.({block:"nearest",behavior:"smooth"});},[data?.state.turns.length,busy]);
 useEffect(()=>{if(data?.characters&&speaker!=="an"&&!data.characters[data.state.position.paragraph]?.some(c=>c.id===speaker))setSpeaker("an");},[data?.state.position.paragraph,speaker,data?.characters]);
 const setState=(state:ReaderState)=>setData(d=>d?{...d,state}:d);
 const savePosition=async(p:Position)=>{if(!data)return;setState(await request<ReaderState>("/companion/position",{position:p,revision:data.state.revision}));};
 const act=async(label:string,fn:()=>Promise<void>)=>{if(busy)return;setBusy(label);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"操作未完成");}finally{setBusy("");}};
 const focusParagraph=(id:number)=>{if(continuous)paper.current?.querySelector(`[data-paragraph="${id}"]`)?.scrollIntoView?.({block:"start",behavior:"smooth"});};
 const choose=(id:number)=>act("正在保存阅读位置",async()=>{await savePosition({...data!.state.position,paragraph:id});focusParagraph(id);});
 const prepareQuestion=(paragraph:number,nextSpeaker:string,message:string)=>act("正在定位原文",async()=>{await savePosition({...data!.state.position,paragraph});setSpeaker(nextSpeaker);setInput(message);setPanel("chat");setMobile(true);setCollapsed(false);});
 const ask=(action="chat",message=input)=>act(action==="translate"?"正在翻译选中的段落":"正在生成回答",async()=>{
  if(!data)return;const controller=new AbortController();abort.current=controller;setAttemptMetrics(undefined);
  try{setState(await conversation({request_id:crypto.randomUUID(),revision:data.state.revision,speaker:action==="translate"?"an":speaker,paragraph:data.state.position.paragraph,action,message,research,style},controller.signal,setBusy,setAttemptMetrics));if(action==="chat")setInput("");else setDisplay("parallel");}
  catch(e){if(controller.signal.aborted){setError("已停止等待。正在核对是否已经保存…");await reload();setError("已停止；下方仅显示服务器确认保存的记录。");}else throw e;}finally{abort.current=null;}
 });
 if(!data)return <main className="cr-loading"><BookOpen size={34}/><h1>正在加载作品</h1><p>{error||"正在读取原文和阅读进度。"}</p>{error&&<button onClick={()=>location.reload()}>重新打开</button>}</main>;
 const s=data.state,p=s.position,ps=data.paragraphs,page=Math.floor((p.paragraph-1)/5),pages=Math.ceil(ps.length/5),visible=continuous?ps:ps.slice(page*5,page*5+5),people=data.characters?.[p.paragraph]||book.characters,person=people.find(c=>c.id===speaker);
 const turns=s.turns.filter(t=>t.speaker===speaker&&t.action==="chat");
 const translations=new Map(s.turns.filter(t=>t.action==="translate").map(t=>[t.paragraph,t.reply]));
 const percent=Math.round((p.finished?ps.length:p.furthest)/ps.length*100);
 const readScenes=book.scenes.filter(scene=>scene.evidence_ids.length>0&&scene.evidence_ids.every(id=>{const ex=book.excerpts?.[id];return !!ex&&(p.full||ex.end_byte<=ps[p.paragraph-1].end_byte);}));
 return <div className={`cr-room ${continuous?"cr-continuous":""} ${collapsed?"cr-panel-hidden":""}`}>
  <header className="cr-header">{onLesson&&<button onClick={onLesson}>← 回到专题</button>}<a href="/reading?view=shelf"><ArrowLeft size={17}/>书架</a><a className="cr-brand" href="/reading"><BookOpen size={21}/>书中见</a><div><button className="cr-desktop-toggle" onClick={()=>setCollapsed(!collapsed)}>{collapsed?"显示伴读":"收起伴读"}</button><button className="cr-finish-shortcut" disabled={!!busy} onClick={()=>setFinishDialog(true)}>读完之后</button><span className="cr-mode">伴读 · 原著不会改变</span><button onClick={()=>setMobile(!mobile)} className="cr-mobile-toggle" aria-label="打开伴读"><MessageCircle size={18}/></button></div></header>
  <div className="cr-workspace">
   <aside className="cr-index"><span className="cr-kicker">当前作品</span><div className="cr-mini-cover" data-book={book.id}><span>{book.author}</span><strong>{book.title}</strong></div><h2>{book.title}</h2><p>{book.author}</p><div className="cr-progress"><i style={{width:`${percent}%`}}/></div><small>{p.finished?"已读完 · 随时重读":`阅读进度 ${percent}%`}</small>
    <div className="cr-index-section"><span className="cr-kicker">阅读工具</span><button className={panel==="chat"?"selected":""} onClick={()=>{setPanel("chat");setMobile(true);setCollapsed(false);}}><Sparkles size={17}/>伴读对话</button><button className={panel==="notes"?"selected":""} onClick={()=>{setPanel("notes");setMobile(true);setCollapsed(false);}}><Feather size={17}/>阅读笔记 <small>{s.notes.length}</small></button></div>
    <div className="cr-bookmarks"><span className="cr-kicker">书签</span>{!p.bookmarks.length?<p>暂无书签。点击原文上方的书签按钮添加。</p>:p.bookmarks.map(id=><button disabled={!!busy} key={id} onClick={()=>choose(id)}><Bookmark size={13}/>第 {id} 段</button>)}</div>
    <div className="cr-index-bottom"><button disabled={!!busy} onClick={()=>setFinishDialog(true)}>{book.read_only?"结束阅读":p.finished?"尝试改写故事":"我已经读完了"}<ArrowRight size={15}/></button></div>
   </aside>
   <main ref={paper} className="cr-paper" style={{"--reader-font":`${font}px`,"--reader-line":lineHeight} as React.CSSProperties}>
    <div className="cr-paper-toolbar"><label>阅读方式<select aria-label="阅读方式" value={display} onChange={e=>setDisplay(e.target.value)}><option value="original">原文</option>{bookTranslation.enabled&&<><option value="parallel">原文 / 译文对照</option><option value="translation">译文</option></>}</select></label><label className="cr-line-control">行距<select aria-label="阅读行距" value={lineHeight} onChange={e=>setLineHeight(e.target.value)}><option value="1.7">紧凑</option><option value="1.9">适中</option><option value="2.2">宽松</option></select></label><div><button aria-label="缩小字号" onClick={()=>setFont(n=>Math.max(16,n-2))}>A−</button><button aria-label="放大字号" onClick={()=>setFont(n=>Math.min(30,n+2))}>A＋</button><button aria-label="为当前段落添加书签" disabled={!!busy} className={p.bookmarks.includes(p.paragraph)?"marked":""} onClick={()=>act("正在保存书签",()=>savePosition({...p,bookmarks:p.bookmarks.includes(p.paragraph)?p.bookmarks.filter(x=>x!==p.paragraph):[...p.bookmarks,p.paragraph]}))}><Bookmark size={17}/></button></div></div>
    <div className="cr-paper-heading"><span className="cr-kicker">{continuous?(book.text_scope||"完整原文"):"原文"}</span><h1>{book.title}</h1><p>{book.author}<span>·</span>{continuous?`${book.text_scope||"全文"} · ${ps.length} 段`:`第 ${page+1} / ${pages} 页`}</p></div>
    <div className="cr-selection-bar">{lesson&&<button onClick={()=>{setPanel("guide");setMobile(true);setCollapsed(false);}}>专题导读</button>}{!book.read_only&&<button onClick={()=>setContextOpen(true)}>人物与场景</button>}<span>讨论第 {p.paragraph} 段</span><button disabled={!!busy} onClick={()=>{setSpeaker("an");setInput("请结合这段原文，帮我理解其中的意思和表达。");setMobile(true);setCollapsed(false);setPanel("chat");}}><Sparkles size={14}/>问安</button>{bookTranslation.enabled&&<button onClick={()=>setDisplay("parallel")}><Languages size={14}/>查看译文</button>}<button onClick={()=>{setPanel("notes");setMobile(true);setCollapsed(false);}}><Feather size={14}/>写笔记</button></div>
    {lessonError&&<p className="cr-error" role="status">{lessonError}</p>}
    {continuous&&<div className="cr-reading-location"><label>定位原文<select aria-label="定位原文段落" value={p.paragraph} disabled={!!busy} onChange={e=>choose(Number(e.target.value))}>{ps.map(par=><option key={par.id} value={par.id}>第 {par.id} 段</option>)}</select></label><button onClick={()=>focusParagraph(p.paragraph)}>回到讨论位置 § {p.paragraph}</button></div>}
    <BookTranslationBar translation={bookTranslation} onShow={()=>setDisplay("parallel")}/>
    <article className="cr-text" aria-label="作品正文">{visible.map(par=>{const sentences=bookTranslation.edition?.sentences.filter(s=>s.paragraph===par.id)||[];const paired=display!=="original"&&sentences.some(s=>s.translation);return <section data-paragraph={par.id} className={`cr-paragraph ${par.id===p.paragraph?"current":""}`} key={par.id}><button className="cr-paragraph-number" aria-label={`选择第${par.id}段`} disabled={!!busy} onClick={()=>choose(par.id)}>{String(par.id).padStart(2,"0")}</button>{paired?<SentenceTranslation sentences={sentences} display={display} busy={bookTranslation.running||!!bookTranslation.edition?.pending||bookTranslation.edition?.completed!==bookTranslation.edition?.total} onRetranslate={id=>void bookTranslation.start(true,id)}/>:<>{display!=="translation"&&<p lang={book.language|| (book.id==="kong"?"zh":"en")}>{par.text}</p>}{display!=="original"&&(translations.has(par.id)?<div className="cr-translation"><small>以前保存的个人段落译文</small><p>{translations.get(par.id)}</p></div>:<div className="cr-untranslated"><Languages size={14}/><span>此段尚无默认译文。可在上方生成并保存全书逐句译本。</span></div>)}</>}</section>;})}</article>
    {continuous?<nav className="cr-pagination" aria-label="原文结尾"><span>{book.text_scope?"选文结束":"全文结束"} · {ps.length} 段</span><button disabled={!!busy} onClick={()=>setFinishDialog(true)}>结束阅读<Check size={16}/></button></nav>:<nav className="cr-pagination" aria-label="阅读翻页"><button disabled={!!busy||page===0} onClick={()=>choose((page-1)*5+1)}><ArrowLeft size={16}/>上一页</button><label>跳到第<select aria-label="跳转页码" disabled={!!busy} value={page} onChange={e=>choose(Number(e.target.value)*5+1)}>{Array.from({length:pages},(_,i)=><option value={i} key={i}>{i+1}</option>)}</select>页</label>{page<pages-1?<button disabled={!!busy} onClick={()=>choose((page+1)*5+1)}>下一页<ArrowRight size={16}/></button>:<button disabled={!!busy} onClick={()=>setFinishDialog(true)}>结束阅读<Check size={16}/></button>}</nav>}
    <footer className="cr-source"><a href={book.source_url} target="_blank" rel="noreferrer">版本与原文出处 ↗</a><p>{book.source_note}</p><small>点击段落编号选择讨论位置。翻页不调用模型，伴读不会改变原著。</small></footer>
   </main>
   <aside className={`cr-companion ${mobile?"mobile-open":""}`} aria-label="伴读面板"><div className="cr-companion-heading"><span className="cr-an">{speaker==="an"?"安":person?.initial}</span><div><strong>{panel==="guide"?"专题导读":panel==="notes"?"阅读笔记":speaker==="an"?"与安一起读":`与${person?.name}聊聊`}</strong><small>{speaker==="an"?"解释原文 · 讨论背景":"人物视角演绎 · 不改变剧情"}</small></div><button className="cr-mobile-close" onClick={()=>setMobile(false)} aria-label="关闭伴读"><X size={18}/></button></div>
    {lesson&&<nav className="cr-panel-tabs" aria-label="伴读侧栏"><button aria-pressed={panel==="chat"} onClick={()=>setPanel("chat")}>对话</button><button aria-pressed={panel==="guide"} onClick={()=>setPanel("guide")}>专题</button><button aria-pressed={panel==="notes"} onClick={()=>setPanel("notes")}>手记 / 理解卡</button></nav>}
    {panel==="guide"&&error&&<p className="cr-error" role="alert">{error}</p>}
    {panel==="guide"&&lesson?<LessonGuide lesson={lesson} people={people} full={p.full||!!book.read_only} paragraph={p.paragraph} busy={!!busy} onSelect={id=>act("正在定位原文",async()=>{await savePosition({...p,paragraph:id});focusParagraph(id);setMobile(false);})} onAsk={prepareQuestion}/>:panel==="chat"?<><label className="cr-speaker-label">对话对象<select aria-label="伴读对象" value={speaker} disabled={!!busy} onChange={e=>setSpeaker(e.target.value)}><option value="an">安 · 作品与背景</option>{people.map(c=><option key={c.id} value={c.id}>{c.name} · 人物视角</option>)}</select></label><div className="cr-scope"><span>{p.full?"允许全书讨论":"跟随当前阅读位置"}</span><button disabled={!!busy} onClick={()=>p.full?act("切换讨论范围",()=>savePosition({...p,full:false})):setReveal(true)}>{p.full?"收起后续":"展开全书"}</button></div>
     <div className="cr-messages">{!turns.length&&<div className="cr-welcome"><h3>{speaker==="an"?"这段有什么不明白的？":"从人物的角度讨论"}</h3><p>{speaker==="an"?"可以问字词含义、表达方式，也可以讨论作者和时代背景。":"可以询问人物的选择和处境。回答是人物视角的模拟，不会改变原著。"}</p>{speaker==="an"&&<button onClick={()=>setInput("这段描写中的时代背景，有哪些是我需要了解的？")}>了解时代背景<ArrowRight size={14}/></button>}</div>}{turns.map(t=><div className="cr-turn" key={t.id}><div className="cr-user"><small>你 · 第 {t.paragraph} 段</small><p>{t.message}</p></div><div className="cr-reply"><small>{t.needs_spoiler?"阅读范围提示":speaker==="an"?"安":person?.name}</small>{(t.research_status==="no_usable_sources"||t.research_status==="unavailable"||t.research_status==="curated_only")&&<div className="cr-research-warning">本次联网未取得可用来源；下方若有“已整理背景”，仅代表预置资料，不是本轮研究成果。</div>}<p>{t.reply}</p><CompanionCost metrics={t.metrics}/>{t.needs_spoiler&&<button onClick={()=>setReveal(true)}>允许全书讨论</button>}{t.evidence?.length>0&&<div className="cr-evidence">原文依据 {t.evidence.map(id=><button key={id} disabled={!!busy} onClick={()=>choose(id)}>§ {id}</button>)}</div>}{t.sources?.map(src=><details className="cr-background" key={src.id}><summary><Globe2 size={13}/>{src.title||"背景来源"}</summary><p>{src.summary}</p><a href={src.url} target="_blank" rel="noreferrer">{src.id.startsWith("curated-")?"打开已整理背景出处 ↗":"打开实际读取的来源 ↗"}</a></details>)}</div></div>)}{busy&&<div className="cr-status" role="status"><LoaderCircle size={16}/>{busy}</div>}<div ref={bottom}/></div>
     <CompanionCost metrics={attemptMetrics} label="最近一次请求"/>
     {speaker==="an"&&data.research_available&&<div className="cr-search-channel" role="note">{data.research_provider==="bing"?"搜索：Bing RSS · 无需新增 Key":data.research_provider==="duckduckgo"?"搜索：DuckDuckGo · 无需新增 Key":data.research_provider==="brave"?"搜索：Brave API · 独立搜索额度":"搜索：已接入背景查询"}<small>配置已接入不代表每次都有结果；回答仍使用当前模型并消耗模型用量。</small></div>}
     <div className="cr-compose">{error&&<p className="cr-error" role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();if(input.trim())ask();}}><textarea aria-label="伴读问题" placeholder={speaker==="an"?"输入问题或你的理解…":`想问${person?.name}什么？`} value={input} onChange={e=>setInput(e.target.value)} maxLength={2000} disabled={!!busy}/>{busy&&abort.current?<button type="button" aria-label="停止回答" onClick={()=>abort.current?.abort()}><Square size={17}/></button>:<button aria-label="发送伴读问题" disabled={!!busy||!input.trim()}><Send size={17}/></button>}</form><div className="cr-compose-options">{speaker==="an"&&<label><input type="checkbox" checked={research} disabled={!data.research_available||!!busy} onChange={e=>setResearch(e.target.checked)}/><Globe2 size={12}/>{data.research_available?"按需查阅公开背景":"背景检索未接入"}</label>}</div><small>公开来源可能覆盖有限；这里只显示回答、依据和工具状态。</small></div></>:<div className="cr-notes"><p>记录对当前段落的理解或疑问。</p><label>第 {p.paragraph} 段<textarea aria-label="阅读笔记" value={note} onChange={e=>setNote(e.target.value)} maxLength={4000}/></label><button disabled={!!busy||!note.trim()} onClick={()=>act("正在保存笔记",async()=>{setState(await request<ReaderState>("/companion/notes",{paragraph:p.paragraph,text:note,revision:s.revision}));setNote("");})}>保存笔记<Feather size={15}/></button>{error&&<p role="alert">{error}</p>}{s.notes.map(n=><article key={n.id}><button disabled={!!busy} onClick={()=>choose(n.paragraph)}>§ {n.paragraph}</button><p>{n.text}</p></article>)}<button onClick={()=>setPanel("chat")}>回到伴读对话</button></div>}
   </aside>
  </div>
  {(finishDialog||reveal)&&<div className="cr-backdrop"><section role="dialog" aria-modal="true" aria-label={reveal?"展开全书讨论":"读完之后"} className="cr-dialog"><button className="cr-dialog-close" aria-label="关闭" onClick={()=>{setFinishDialog(false);setReveal(false);}}><X size={20}/></button><h2>{reveal?"允许讨论后续内容？":"读完之后"}</h2><p>{reveal?"安可以结合全书讨论。人物仍只拥有所处时刻的认知；外部链接也可能包含后续内容。":book.read_only?"可以继续讨论全文，或保存阅读笔记。本篇不提供故事改写。":"可以继续讨论全文，也可以选择一个场景，尝试改变故事走向。改写会单独保存，不影响原著。"}</p>{reveal?<button className="cr-primary" disabled={!!busy} onClick={()=>act("正在展开讨论范围",async()=>{await savePosition({...p,full:true});setSpeaker("an");setReveal(false);})}>允许全书讨论</button>:<>{!book.read_only&&<button className="cr-primary" disabled={!!busy} onClick={()=>act("正在记录阅读完成",async()=>{await savePosition({...p,finished:true,full:true});setFinishDialog(false);onStory();})}>尝试改写故事<ArrowRight size={17}/></button>}<button disabled={!!busy} onClick={()=>act("正在保存读完状态",async()=>{await savePosition({...p,finished:true,full:true});setFinishDialog(false);setSpeaker("an");setInput("我读完了，想和你讨论对这篇作品的整体理解。");setPanel("chat");setMobile(true);setCollapsed(false);})}>与安讨论全文</button></>}{error&&<p role="alert">{error}</p>}</section></div>}
  {contextOpen&&<div className="cr-backdrop"><section className="cr-dialog cr-context-dialog" role="dialog" aria-modal="true" aria-label="已读人物与场景"><button className="cr-dialog-close" aria-label="关闭人物与场景" onClick={()=>setContextOpen(false)}><X size={20}/></button><h2>已读人物与场景</h2><p>只展开当前阅读范围内的场景。同场出现不等于彼此知道全部秘密。</p><h3>当前可交流的人物</h3><div className="cr-context-people">{people.map(c=><button key={c.id} onClick={()=>{setSpeaker(c.id);setPanel("chat");setMobile(true);setCollapsed(false);setContextOpen(false);}}>{c.name}</button>)}</div><h3>已展开的场景</h3>{readScenes.length===0?<p>故事刚刚开始。场景的原文读到之后，这里会逐步展开。</p>:<ol>{readScenes.map(scene=><li key={scene.id}><strong>{scene.title}</strong><p>{scene.characters.map(id=>book.characters.find(c=>c.id===id)?.name).filter(Boolean).join(" · ")}</p></li>)}</ol>}<small>编者整理的场景索引；不是模型自动生成的人物关系。</small></section></div>}
 </div>;
}
